name: mama_pill
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '^3.7.2'
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  connectivity_plus: ^6.1.1
  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  get_it: ^8.0.3
  table_calendar: ^3.1.3
  intl: ^0.19.0
  firebase_database: ^11.2.0
  flutter_local_notifications: ^18.0.1
  rxdart: ^0.28.0
  timezone: ^0.10.0
  sliver_tools: ^0.2.12
  flutter_sticky_header: ^0.7.0
  shared_preferences: ^2.2.2
  another_flushbar: ^1.12.30
  encrypt: ^5.0.3
  # flutter_native_timezone: ^2.0.0


dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons :
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/foreground_icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
